/* clientes.js — atendimento ao cliente: busca de horários, cadastro e inicialização do app. */
    function clientBookings(phone){const key=phoneKey(phone);return Object.values(data.bookings).filter(b=>phoneKey(b.phone)===key)}
    $("#searchClient").onclick=renderClientResults;$("#clientPhone").addEventListener("keydown",e=>{if(e.key==="Enter")renderClientResults()});$("#clientPhone").addEventListener("input",e=>{e.target.value=maskPhone(e.target.value);clearTimeout(renderClientResults.t);if(phoneKey(e.target.value).length>=10)renderClientResults.t=setTimeout(renderClientResults,350)});
    function renderClientResults(){
      const phone=phoneKey($("#clientPhone").value),items=clientBookings(phone).sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time)),box=$("#clientResults");
      if(phone.length<10){box.innerHTML='<div class="empty">Digite um telefone válido com DDD.</div>';return}if(!items.length){box.innerHTML='<div class="empty">Nenhum agendamento encontrado para este telefone.</div>';return}
      const current=items.filter(b=>b.status!=="cancelled"&&b.status!=="completed"&&b.date>=todayISO()).length,client=items[0];
      box.innerHTML=`<div class="client-profile"><div><small>Contato encontrado</small><strong>${esc(client.name)}</strong><p>${formatPhone(client.phone)}</p></div><div class="client-count"><b>${current}</b><small>ativo${current===1?"":"s"}</small></div></div>`+items.map(b=>{const d=new Date(b.date+"T12:00:00"),canCancel=b.status!=="cancelled"&&b.status!=="completed"&&b.date>=todayISO();return `<article class="booking-item"><div class="date-box"><small>${d.toLocaleDateString("pt-BR",{month:"short"})}</small><strong>${String(d.getDate()).padStart(2,"0")}</strong></div><div><h4>${esc(b.serviceName)}</h4><p>${b.time} · ${money(b.price)}${b.notes?` · ${esc(b.notes)}`:""}</p></div><div class="booking-actions"><span class="status ${b.status}">${statusLabel(b.status)}</span>${canCancel?`<button class="mini no" data-client-cancel="${b.id}">Cancelar</button>`:""}</div></article>`}).join("");
      $$('[data-client-cancel]').forEach(btn=>btn.onclick=async()=>{const booking=data.bookings[btn.dataset.clientCancel];if(!booking||!confirm(`Cancelar ${booking.serviceName} em ${formatDateNumeric(booking.date)} às ${booking.time}?`))return;try{await cancelBooking(booking)}catch(error){console.error("Falha ao cancelar",error);toast("Não foi possível atualizar o cancelamento no Firebase.")}renderClientResults()});
    }
    function statusLabel(s){return ({pending:"A confirmar",confirmed:"Confirmado",completed:"Concluído",cancelled:"Cancelado"})[s]||s}

    function clientsView(){
      const map={};Object.values(data.bookings).forEach(b=>{map[b.phone]=map[b.phone]||{name:b.name,phone:b.phone,count:0,total:0,last:"",notes:""};const x=map[b.phone];if(b.status!=="cancelled"){x.count++;x.total+=Number(b.price)}if(b.date>x.last){x.last=b.date;x.notes=b.notes||x.notes}});const items=Object.values(map);
      return `<div class="panel"><div class="panel-head"><h3>Cadastro e histórico</h3><span class="status">${items.length} clientes</span></div>${items.length?`<div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Telefone</th><th>Visitas</th><th>Última visita</th><th>Preferências</th><th>Ações</th></tr></thead><tbody>${items.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.phone)}</td><td>${x.count}</td><td>${x.last?formatDate(x.last):"—"}</td><td title="${esc(x.notes)}">${esc(x.notes||"—")}</td><td><button class="mini no" data-delete-client="${esc(x.phone)}" data-client-name="${esc(x.name)}">Excluir</button></td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">Os clientes aparecem após o primeiro agendamento.</div>'}</div>`}
    /* --- Inicialização (executa por último, com todos os scripts carregados) --- */
    $$('[data-whatsapp]').forEach(b=>b.onclick=()=>{const n=cleanPhone(data.settings.whatsapp);if(!n)return toast("WhatsApp ainda não configurado no painel");window.open(`https://wa.me/${n}`,"_blank","noopener")});
    $("#year").textContent=new Date().getFullYear();
    window.addEventListener("load",()=>setTimeout(()=>$("#splash").classList.add("done"),3000));
    initStorage();
